resource "local_file" "group_vars" {
  content  = <<-DOC
    ---
    # Ansible group_vars containing variable values from Terraform.
    # Generated by Terraform.

    domain_name: ${var.domain_name}
    sub_domains:
      - name: www
        ip: "${yandex_compute_instance.node04-app.network_interface.0.ip_address}"
        port: 80
      - name: gitlab
        ip: "${yandex_compute_instance.node05-gitlab.network_interface.0.ip_address}"
        port: 80
      - name: grafana
        ip: "127.0.0.1"
        port: 3000
      - name: prometheus
        ip: "127.0.0.1"
        port: 9090
      - name: alertmanager
        ip: "127.0.0.1"
        port: 9093

    test_cert: "${var.test_cert}"
    nginx_local_ip: ${yandex_compute_instance.node01-nginx.network_interface.0.ip_address}

    environment:
      http_proxy: 'http://{{ nginx_local_ip }}:3128'
      https_proxy: 'http://{{ nginx_local_ip }}:3128'

    gitlab_root_password: '${var.gitlab_root_password}'
    gitlab_runner_token: '${var.gitlab_runner_token}'

    DOC
  filename = "../ansible/group_vars/all.yml"

  depends_on = [
    yandex_compute_instance.node01-nginx,
    yandex_compute_instance.node02-db01,
    yandex_compute_instance.node03-db02,
    yandex_compute_instance.node04-app,
    yandex_compute_instance.node05-gitlab,
    yandex_compute_instance.node06-runner
  ]
}