resource "local_file" "group_vars" {
  content  = <<-DOC
    ---
    # Ansible group_vars containing variable values from Terraform.
    # Generated by Terraform.

    domain_name: ${var.domain_name}
    sub_domains:
      - name: www
        ip: "127.0.0.1"
        port: 80
      - name: gitlab
        ip: "127.0.0.1"
        port: 80
      - name: grafana
        ip: "127.0.0.1"
        port: 3000
      - name: prometheus
        ip: "127.0.0.1"
        port: 9090
      - name: alertmanager
        ip: "127.0.0.1"
        port: 9093

    test_cert: "${var.test_cert}"
    nginx_local_ip: ${yandex_compute_instance.node01-nginx.network_interface.0.ip_address}

    DOC
  filename = "../ansible/group_vars/all.yml"

  depends_on = [
    yandex_compute_instance.node01-nginx
  ]
}