resource "local_file" "inventory" {
  content  = <<-DOC
    ---
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.
    nginx:
      hosts:
        node01_nginx:
          ansible_host: ${yandex_compute_instance.node01-nginx.network_interface.0.nat_ip_address}

    master:
      vars:
        mysql_replication_role: "master"
      hosts:
        db01:
          ansible_host: ${yandex_compute_instance.node02-db01.network_interface.0.ip_address}

    slave:
      vars:
        mysql_replication_role: "slave"
      hosts:
        db02:
          ansible_host: ${yandex_compute_instance.node03-db02.network_interface.0.ip_address}

    dbservers:
      children:
        master:
        slave:
      vars:
        database_name: ${var.database_name}
        database_user: ${var.database_user}
        database_password: ${var.database_password}
        mysql_replication_user: ${var.database_replication_user}
        mysql_replication_user_password: ${var.database_replication_user_password}
        mysql_replication_master: ${var.database_replication_masternode}

    behind_proxy:
      vars:
        ansible_ssh_common_args: '-C -o ControlMaster=auto -o ControlPersist=60s -o ServerAliveInterval=30 -o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -q ubuntu@{{ domain_name }}"'
      children:
        dbservers:
        www:
        cicd:
        prometheus:

    www:
      hosts:
        app:
          ansible_host: ${yandex_compute_instance.node04-app.network_interface.0.ip_address}

    cicd:
      hosts:
        gitlab:
          ansible_host: ${yandex_compute_instance.node05-gitlab.network_interface.0.ip_address}
          environment:
            GITLAB_OMNIBUS_CONFIG: "external_url 'http://gitlab.{domain_name}/'; gitlab_rails['initial_root_password'] = '${var.gitlab_root_password}'"
            EXTERNAL_URL: "{domain_name}"
          vars:
            gitlab_root_password: "${var.gitlab_root_password}"
            gitlab_runner_token: "${var.gitlab_runner_token}"
        runner:
          ansible_host: ${yandex_compute_instance.node06-runner.network_interface.0.ip_address}
          vars:
            gitlab_runner_token: "${var.gitlab_runner_token}"

    prometheus:
      hosts:
        monitoring:
          ansible_host: ${yandex_compute_instance.node07-monitoring.network_interface.0.ip_address}

    node_exporter_nodes:
      hosts:
        node01_nginx:
        db01:
        db02:
        app:
    #    gitlab:
        runner:
        monitoring:
    DOC
  filename = "../ansible/inventory/stage.yml"

  depends_on = [
    yandex_compute_instance.node01-nginx,
    yandex_compute_instance.node02-db01,
    yandex_compute_instance.node03-db02,
    yandex_compute_instance.node04-app,
    yandex_compute_instance.node05-gitlab,
    yandex_compute_instance.node06-runner
  ]
}