resource "local_file" "inventory" {
  content = <<-DOC
    ---
    # Ansible inventory containing variabler values from Terraform.
    # Generated by Terraform.
    nginx:
      hosts:
        node01_nginx:
          ansible_host: ${yandex_compute_instance.node01-nginx.network_interface.0.nat_ip_address}
    DOC
  filename = "../ansible/inventory/stage.yml"

  depends_on = [
    yandex_compute_instance.node01-nginx
  ]
}