- name: Install Prometheus and Grafana
  hosts: monitoring
  remote_user: ubuntu
  roles:
    - install-monitoring
  environment:
    http_proxy: 'http://{{ nginx_local_ip }}:3128'
    https_proxy: 'http://{{ nginx_local_ip }}:3128'
