- name: Install nginx
  hosts: nginx
  remote_user: ubuntu
  roles:
    - install-nginx
  post_tasks:
    - name: Nginx - create config file
      become: true
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/conf.d/{{ domain_name }}.conf
      notify: reload-nginx
    - name: Copy - private key to proxy server
      ansible.builtin.copy:
        src: ~/.ssh/id_rsa
        dest: /home/ubuntu/.ssh/id_rsa
        owner: ubuntu
        group: ubuntu
        mode: u+rw,g-rwx,o-rwx
        backup: yes
    - name: Copy - ssh config to reduce strict restrictions on a proxy host
      ansible.builtin.copy:
        src: config.ssh
        dest: /home/ubuntu/.ssh/config
        owner: ubuntu
        group: ubuntu
        mode: u+rw,g+rw,o+r
        backup: yes

