- name: Install Wordpress
  hosts: app
  remote_user: ubuntu
  roles:
    - install-wordpress
  environment:
    http_proxy: 'http://{{ nginx_local_ip }}:3128'
    https_proxy: 'http://{{ nginx_local_ip }}:3128'

