- name: Install proxy for APT
  hosts: behind_proxy
  remote_user: ubuntu
  tasks:
    - name: Configure APT proxy
      become: true
      ansible.builtin.template:
        src: apt_proxy.conf.j2
        dest: /etc/apt/apt.conf.d/proxy.conf
